export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_CART_ITEM = 'FETCH_CART_ITEM';
export const CLEAR_CART = 'CLEAR_CART';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
