export const HOME = '/'
export const PRODUCTS = '/products'
export const ABOUT = '/about'
export const CONTACT = '/contact'
export const CARTS = '/carts'
export const CHECKOUT = '/checkout'
export const JEWELL = '/jewell-collection'
export const CLOTHINGS = '/clothings'