export const HOME = '/'
export const PACKAGES = '/packages'
export const FURNITURE = '/furniture'
export const APPLIANCES = '/appliances'
export const PRODUCTS = '/products'
export const CARTS = '/carts'
export const CHECKOUT = '/checkout'