import Head from "next/head";
import Banner from "../components/Views/Banner";
import Card from "../components/Views/Card";
import CardSection from "../components/Views/CardSection";

export default function Home() {
  return (
    <div className="h-full">
      <Head>
        <title>Ramany Boutique</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Banner />
      <CardSection/>
    </div>
  );
}
