import React from 'react';
import Head from 'next/head';

const PrivacyPolicy = () => {
  return (
    <div>
      <Head>
        <title>The Ramya Boutique</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="relative py-16 overflow-hidden bg-white">
        <div className="relative px-4 sm:px-6 lg:px-8">
          <div className="mx-auto text-lg max-w-prose">
            <h1>
              <span className="block mt-2 text-3xl font-bold leading-8 tracking-tight text-center text-gray-900 sm:text-4xl">
                Privacy Policy
              </span>
            </h1>
          </div>
          <div className="mx-auto mt-6 prose prose-lg text-gray-500 prose-indigo">
            <p>
              The Ramya Boutique respects and is committed to protecting your
              privacy. Publishing, selling, or renting any personal data or
              information to any third party, without your consent is against
              our ethics. The privacy practices described in this statement
              apply to our services available under the domain and sub-domains
              of the Site. By visiting our website, you agree to be bound by the
              terms and conditions of this privacy policy. If you do not agree,
              please do not use or access our site.
            </p>
            <p>
              This privacy policy does not apply to sites maintained by other
              companies or organizations to which we link, and we are not
              responsible for any personal information you submit to third
              parties via our website. Please ensure that you read the privacy
              policies of such other companies or organizations before
              submitting your details.
            </p>
            <p>
              This privacy policy describes the information, as part of the
              normal operation of our services. This policy is inter alia
              formulated and displayed to inform you about our information
              collection and retention policies and practices. So that you can
              make an informed decision in relation to the sharing of your
              personal information with us. By accepting the privacy policy and
              the user agreement or the use of the site in general, you give
              your consent to our use and disclosure of your personal
              information in accordance with this privacy policy. This Privacy
              Policy is incorporated into and subject to the terms of the User
              Agreement. This privacy policy is effective upon acceptance of
              access by you to the site.
            </p>

            <h3>Privacy Guarantee</h3>
            <p>
              We agree that we will not sell or rent your personal information
              to third parties for their marketing purposes without your
              explicit consent. From time to time, we may reveal general
              statistical information about our website and visitors, such as
              the number of visitors, the type of goods and services purchased,
              etc. Only those of our employees who need access to your
              information in order to perform their duties are allowed such
              access. Any employee who violates our privacy and/or security
              policies is subject to disciplinary action, including possible
              termination and civil and/or criminal prosecution.
            </p>

            <h3>Information We Collect</h3>
            <p>
              Personal information is used for two general purposes: to process
              your order and to provide you with the best possible service.
              Unless otherwise stated explicitly, this policy applies to
              personal information as disclosed in any of the media.
            </p>
            <p>
              In furtherance of the confidentiality with which we treat personal
              information, we have put in place appropriate physical,
              electronic, and managerial procedures to safeguard and secure the
              information we collect online. We use data collection devices such
              as &quot;cookies&quot; on certain pages of the website to help
              analyze our web page flow, measure promotional effectiveness, and
              promote trust and safety. &quot;Cookies&quot; are small files
              placed on your hard drive that assist us in providing our
              services. We offer certain features that are only available
              through the use of a &quot;cookie.&quot; Cookies can also help us
              provide information that is targeted to your interests. Most
              cookies are &quot;session cookies,&quot; which means that they are
              automatically deleted from your hard drive at the end of a
              session. You are always free to decline our cookies if your
              browser permits. Additionally, you may encounter
              &quot;cookies&quot; or other similar devices on certain pages of
              the website that are placed by third parties. For example, if you
              view a web page created by a user, there may be a
              &quot;cookie&quot; placed within that web page. We do not control
              the use of cookies by third parties.
            </p>
            <p>
              You acknowledge that you are disclosing Personal Information
              voluntarily. We identify and use your IP address to help diagnose
              problems with our server, and to administer our Website. Your IP
              address is also used to help identify you and to gather broad
              demographic information.
            </p>
            <p>
              You acknowledge that you are disclosing personal information
              voluntarily. We identify and use your IP address to help diagnose
              problems with our server and to administer our website. Your IP
              address is also used to help identify you and to gather broad
              demographic information.
            </p>

            <h3>COOKIE POLICY</h3>
            <p>
              <a href="www.theramyaboutique.com">www.theramyaboutique.com</a>{' '}
              operates a strict privacy policy and we are committed to being
              transparent about how we use cookies on our website.
            </p>

            <h4>Why are cookies important?</h4>
            <p>
              Cookies help you make your online experience more efficient and
              relevant to your interests. For instance, they are used to
              remember your preferences on sites you visit often, to remember
              your user ID and the contents of your shopping baskets, and to
              help you navigate between pages efficiently.
            </p>

            <h4>What is a Cookie?</h4>
            <p>
              A cookie is a small file, or files, on your computer, phone, or
              other device with a browser to save snippets of text for reference
              by the website you are visiting. All cookies have expiration dates
              in them that determine how long they stay in your browser:
            </p>

            <p>
              Session cookies—these are temporary cookies that expire (and are
              automatically erased) whenever you close your browser.
            </p>
            <p>
              Persistent cookies: these usually have an expiration date and so
              stay in your browser until they expire, or until you manually
              delete them. For example, we use persistent cookies to better
              understand usage patterns so that we can improve the site for our
              customers.
            </p>
            <p>Cookies are grouped into the following categories:</p>
            <p>
              Essential: these are cookies that are required for the regular
              operation of our websites.
            </p>
            <p>
              Functional: These remember your preferences and are intended to
              make your experience on our websites better for you.
            </p>
            <p>
              Analytics: these cookies are used for performance measurement to
              understand things like how many people visit our websites, how
              they navigate our sites, and what content is popular.{' '}
            </p>
            <p>
              Advertising: These cookies enable us and our advertising partners
              to serve you with relevant advertisements that we think will
              interest you. You might see these advertisements on our websites
              or on other websites you visit. These cookies record your visit to
              our website and the content you interact with. They may be placed
              by us, or by advertising partners with our permission.
            </p>
            <p>
              To ensure compliance with our policies, we restrict the use of
              third-party cookies to trusted partners.
            </p>
            <p>
              We also use third-party information from third-party sources to
              enable us to deliver advertising. These sources are validated by a
              third party and not by us.
            </p>
            <p>
              To delete cookies from your browser, please follow the simple
              steps below. The following steps are indicative of Google Chrome
              and might vary for the different browsers that you may use. Please
              refer to the settings on your browser for further details.
            </p>
            <p>
              To ensure compliance with our policies, we restrict the use of
              third-party cookies to trusted partners.
            </p>
            <p>
              You may also change other setting related to Privacy and Security
              under the same section.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
